### ISSUE TITLE
Reward tokens

### ISSUE THREAD

**Issue by Arrthuur** [merkle3/lending-contracts#1]
I was told when pitched the idea that there would be 5M reward tokens issued over 5 years. I see here your TODO has only 4M.......... Brining attention to this!

https://github.com/merkle3/lending-contracts/blob/d2f0e2a71fcc8d399b2aca80b38d0f1aacc1a2aa/src/markets/MToken.sol#L76

**Comment by Theo-** [comment]
fixed in d1a4b9c7d313432f88096c6d7e41771d373ba832 !
